### ISSUE TITLE
Segmentation Fault no programa

### ISSUE THREAD

**Issue by iWarhead** [iWarhead/RobotsInfo#2]
Adicionei a maioria das funções, algumas estão em formatos de teste ainda, mas ao executar o programa e dar o primeiro comando de movimento, o programa dá segmentation fault.
Acredito que o erro está na função robojoga(), mas não sei exatamente onde, estou rodando testes no momento e aceito ajuda, se possível.

**Comment by eilins** [comment]
Arthur, se o erro tu já tem noção que está na função robojoga(), dentro dele cria vários debugs, exemplo, varios printf (blablabla); isso dentre as chamadas das funções, ai tu vai vê ate onde o programa está rodando e a partir dali tu vê onde pode ta o possível erro.

**Comment by iWarhead** [comment]
Valeu vinícius, fiz isso aqui e a aparentemente o erro está ná função movimenta!, mais precisamente no meio dela, pois o printf funcionou no começo, e não no final.
