### ISSUE TITLE
Erros de compilação

### ISSUE THREAD

**Issue by drbeco** [iWarhead/RobotsInfo#3]
Ao tentar compilar com:

```
$ make robots.x
```

O `gcc` retornou os seguintes erros:

```
robots.c: In function ‘main’:
robots.c:35:5: warning: suggest parentheses around assignment used as truth value [-Wparentheses]
     }while(retorno=0);
     ^
robots.c: In function ‘robojoga’:
robots.c:180:5: warning: statement with no effect [-Wunused-value]
     f==0;
     ^
robots.c:217:9: warning: suggest parentheses around assignment used as truth value [-Wparentheses]
         if(xh=x) /* Humano nao esta a esquerda nem a direita do robo, robo nao se move horizontalmente */
         ^
robots.c:271:9: warning: suggest parentheses around assignment used as truth value [-Wparentheses]
         if(yh=y)
         ^
robots.c:193:23: warning: ‘z’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         d.mapa[x--][y]=z;
                       ^
```

**Comment by iWarhead** [comment]
Sim, professor, o programa ainda está incompleto, estou tentando resolver uns conflitos, e ao conseguir colocar as funções para funcionar corretamente, irei corrigir esses warnings.

**Comment by drbeco** [comment]
O programa nunca vai funcionar se o que você programa **diz** para ele fazer algo diferente do que **quer**.

`warning: suggest parentheses around assignment used as truth value`

Tem **vários** desse, e isso muda tudo. Elimine os bugs de compilação primeiro, antes de tentar eliminar os bugs de lógica.

**Comment by iWarhead** [comment]
Farei.

**Comment by iWarhead** [comment]
Resolvido todos os warnings, agora os erros mudaram, tentarei resolvê-los. Valeu (mais uma vez) pela sugestão professor.

**Comment by drbeco** [comment]
A hora que puder, dá um push no develop para eu olhar. E fecha esse bug. Crie outros para cada warning / error que precisar discutir com sua dupla. 

Aliás, cadê a dupla aqui respondendo?

**Comment by iWarhead** [comment]
O senhor quer um push agora sem os warnings? Posso fazê-lo.

**Comment by drbeco** [comment]
Comentário acima:

---

A hora que puder, dá um push no develop para eu olhar. E fecha esse bug. Crie outros para cada warning / error que precisar discutir com sua dupla.

Aliás, cadê a dupla aqui respondendo?
