### ISSUE TITLE
O humano não anda!

### ISSUE THREAD

**Issue by iWarhead** [iWarhead/RobotsInfo#4]
Por algum motivo o humano não está andando, já atualizei o remoto com as alterações mais recentes, e após varias edições e testes ainda não consegui encontrar o erro. Sugestões?

**Comment by drbeco** [comment]
Dá `segmentation fault` que é um erro de acesso indevido de área de memória.

Para saber em que linha deu erro faça o seguinte procedimento:

```
$ ulimit -c unlimited
$ ./robots.x
```

Após o erro, vai aparecer a mensagem `core dumped` e um arquivo para análise _post mortem_ chamado `core` será criado. Para analisá-lo, faça:

```
$ gdb robots.x core
gnu gdb (Debian...)
(gdb)
```

Esse `(gdb)` é o prompt do debugger. Para saber mais sobre ele, leia o arquivo **09-msg-debug.txt** no dropbox.

Você pode então digitar:

```
(gdb) frame
(gdb) l                     <<<<<letra "l" de list
(gdb) bt                   <<<<< abrev. de backtrace
```

Com isso você irá descobrir em que linha travou o programa.

Também pode ver os valores das variáveis antes do programa terminar, com o comando `print` (letra `p`). Recomendo imprimir os valores dos índices dos vetores `x` e `y`, pois o erro é de acesso indevido de memória.

```
(gdb) p y
```

**Comment by iWarhead** [comment]
Tentei usar o debug antes mas não tinha entendido como funcionava o core dump. Obrigado pela dica professor.

**Comment by iWarhead** [comment]
O erro que está dando na versão mais atual não é segmentation fault, na verdade ele permite você digitar a tecla para se mover, mas após o enter, nada acontece, ele simplesmente pula uma linha.

**Comment by drbeco** [comment]
Meu ramo está atualizado e deu `segmentation fault`. Se você não deu `push` e eu estou testando um ramo diferente do seu, perdemos tempo, que é valoroso.

Aqui deu a variável `y` valendo `-433`!

**Comment by drbeco** [comment]
Debug:

```
$ ./robots.x 

- - - - - - - - - - - -
| . . . . . H . . . . |
| . . . . . . . . . . |
| . . . . . . . . . . |
| . . . R . . . . . . |
| . . . . . . . . . . |
| . . . . . . . . . . |
| . . R . . . . . . . |
| . . . . . . . . . . |
| P . . . . . . . . . |
| . . . . . . . . . . |
- - - - - - - - - - - -

Controles:
   w
 a   d        (t) - Teleporte
   s
a
Segmentation fault (core dumped)
$ gdb robots.x core
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
...
(gdb) frame
#0  0x0000000000400da1 in robojoga () at robots.c:185
warning: Source file is more recent than executable.
185                 }
(gdb) list
180                 if(x!=9 && d.mapa[x+1][y]==0)
181                 {
182                     d.mapa[x+1][y]=2;
183                     d.mapa[x][y]=0;
184                     v=0;
185                 }
186                 else
187                 {
188                     printf("Movimento invalido!\n");
189                     v=1;
(gdb) p y
$1 = -433
(gdb)
```

**Comment by iWarhead** [comment]
Bom, ao dar git diff develop origin/develop não aparece nenhuma diferença, de qualquer maneira no meu programa está dando a seguinte saida:
http://sprunge.us/EPiS

**Comment by iWarhead** [comment]
Muito estranho, ao iniciar o programa, caso eu comece com w, ele mostra o printf de movimento invalido, mas caso eu comece com qualquer outra tecla, ele simplesmente pula linhas.

**Comment by matheusmoraismoura** [comment]
Vou dar uma olhada na função de novo.

**Comment by iWarhead** [comment]
O erro já não é mais o da minha mensagem anterior, da uma olhada no ultimo issue que eu criei.
